spring:
  application:
    name: word
  config:
    import: application-jwt.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/noahDatabase
    username: root
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver